data_transformation:
  test_size: 0.2
  random_state: 42
  max_features: 50000
  ngram_range: [1, 2]
  lowercase: true
  stop_words: english

model_trainer:
  random_state: 42
  max_iter: 200
  C: 1.0
  solver: lbfgs
  n_jobs: -1
  # class_weight: {"0": 1.0, "1": 1.0}
